shaders = {
'snd_BeamShield': [
('scroll_light0', 'float2', (0.0, 0.0)),
('scroll_light1', 'float2', (0.0, 0.0)),
('light0_color', 'float3', (4.0, 0.5, 0.5)),
('light1_color', 'float3', (0.5, 0.5, 2.0)),
('alpha', 'float', 1.0),
('light0_tex', 'texture'),
('light1_tex', 'texture')
],
'snd_Chara_2ColorChange': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('change_color0', 'float3', (1.0, 0.0, 0.0)),
('change_color1', 'float3', (0.0, 0.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_cm0_cm1_occ', 'texture'),
('param_reflect_specpow_specint', 'texture')
],
'snd_Chara_Alpha': [
('diffuse', 'float4', (1.0, 1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('translucent_fall_off_amount', 'float', 1.0),
('translucent_fall_off_scale', 'float', 1.0),
('translucent_fall_off_offset', 'float', 1.0),
('albedo', 'texture_alpha'),
('normal', 'normal'),
('param_reflect_specpow_specint_occ', 'texture_alpha')
],
'snd_Chara_Basic': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_specpow_specint_occ', 'texture_alpha')
],
'snd_Chara_Basic_Light_damage': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('light_color', 'float3', (4.0, 0.5, 0.5)),
('damage_uv_mul', 'float2', (10.0, 10.0)),
('damage_mask_uv_mul', 'float2', (10.0, 10.0)),
('damage_normal_amount', 'float', 1.0),
('damage_specular_pow', 'float', 100.0),
('damage_specular_color', 'float3', (1.0, 1.0, 1.0)),
('damage_edge_color', 'float3', (1.0, 1.0, 1.0)),
('damage_max_color', 'float3', (0.2, 0.1, 0.1)),
('damage_reflection', 'float', 0.0),
('damage_metallic', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_specpow_specint_occ', 'texture_alpha'),
('param_light_mask', 'texture'),
('damage_dist', 'texture'),
('damage_diffuse', 'texture'),
('damage_normal', 'normal')
],
'snd_Chara_Basic_damage': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('damage_uv_mul', 'float2', (10.0, 10.0)),
('damage_mask_uv_mul', 'float2', (10.0, 10.0)),
('damage_normal_amount', 'float', 1.0),
('damage_specular_pow', 'float', 100.0),
('damage_specular_color', 'float3', (1.0, 1.0, 1.0)),
('damage_edge_color', 'float3', (1.0, 1.0, 1.0)),
('damage_max_color', 'float3', (0.2, 0.1, 0.1)),
('damage_reflection', 'float', 0.0),
('damage_metallic', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_specpow_specint_occ', 'texture_alpha'),
('damage_dist', 'texture'),
('damage_diffuse', 'texture'),
('damage_normal', 'normal')
],
'snd_Chara_Basic_damageLight': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('damage_uv_mul', 'float2', (10.0, 10.0)),
('damage_mask_uv_mul', 'float2', (10.0, 10.0)),
('damage_normal_amount', 'float', 1.0),
('damage_specular_pow', 'float', 100.0),
('damage_specular_color', 'float3', (1.0, 1.0, 1.0)),
('damage_edge_color', 'float3', (1.0, 1.0, 1.0)),
('damage_max_color', 'float3', (0.2, 0.1, 0.1)),
('damage_reflection', 'float', 0.0),
('damage_metallic', 'float', 0.0),
('damage_light', 'float', 1.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_specpow_specint_occ', 'texture_alpha'),
('damage_dist', 'texture'),
('damage_diffuse', 'texture'),
('damage_normal', 'normal')
],
'snd_Chara_Decoy_damage': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('damage_mask_uv_mul', 'float2', (10.0, 10.0)),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_specpow_specint_occ', 'texture_alpha'),
('damage_dist', 'texture'),
('damage_albedo', 'texture'),
('damage_normal', 'normal'),
('damage_param_reflect_specpow_specint_occ', 'texture_alpha')
],
'snd_Chara_Decoy_damage_clip': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('damage_mask_uv_mul', 'float2', (10.0, 10.0)),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_specpow_specint_occ', 'texture_alpha'),
('damage_dist', 'texture')
],
'snd_Chara_Decoy_uvAnm': [
('anim_pattern_max', 'float', 4.0),
('anim_pattern_no', 'float', 0.0),
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_specpow_specint_occ', 'texture_alpha')
],
'snd_Chara_FencerEnergyShield': [
('diffuse', 'float4', (1.0, 1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('translucent_fall_off_amount', 'float', 1.0),
('translucent_fall_off_scale', 'float', 1.0),
('translucent_fall_off_offset', 'float', 1.0),
('albedo', 'texture_alpha'),
('normal', 'normal'),
('param_reflect_XXX_spec_hspec', 'texture_alpha')
],
'snd_Common_Basic': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_occ', 'texture')
],
'snd_Common_Light_NoOcc': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('light_color', 'float3', (4.0, 0.5, 0.5)),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_lightmask_hlightmask', 'texture_alpha')
],
'snd_Common_Simple_NoLight': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('albedo', 'texture')
],
'snd_Debris_Chara_Basic': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_specpow_specint_occ', 'texture_alpha')
],
'snd_Debris_Common_Basic': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_occ', 'texture')
],
'snd_Dino_LightScroll': [
('scroll_light0', 'float2', (0.0, 0.0)),
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('light0_color', 'float3', (4.0, 0.5, 0.5)),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_light0mask_hlight0mask', 'texture_alpha'),
('light0_scroll', 'texture'),
('param_occ_XXX_XXX_XXX', 'texture')
],
'snd_Dino_LightScroll_damage': [
('scroll_light0', 'float2', (0.0, 0.0)),
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('light0_color', 'float3', (4.0, 0.5, 0.5)),
('damage_uv_mul', 'float2', (10.0, 10.0)),
('damage_mask_uv_mul', 'float2', (10.0, 10.0)),
('damage_normal_amount', 'float', 1.0),
('damage_specular_pow', 'float', 100.0),
('damage_specular_color', 'float3', (1.0, 1.0, 1.0)),
('damage_edge_color', 'float3', (1.0, 1.0, 1.0)),
('damage_max_color', 'float3', (0.2, 0.1, 0.1)),
('damage_reflection', 'float', 0.0),
('damage_metallic', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_light0mask_hlight0mask', 'texture_alpha'),
('light0_scroll', 'texture'),
('param_occ_XXX_XXX_XXX', 'texture'),
('damage_dist', 'texture'),
('damage_diffuse', 'texture'),
('damage_normal', 'normal')
],
'snd_Map_Build_Basic': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('change_color', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('dirt_adjust', 'float', 0.8),
('albedo', 'texture'),
('normal', 'normal'),
('dirt', 'texture_alpha'),
('param_reflect_cm0_spec_hspec', 'texture_alpha'),
('param_occlusion', 'texture')
],
'snd_Map_Build_Basic_NC': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('dirt_adjust', 'float', 0.8),
('albedo', 'texture'),
('normal', 'normal'),
('dirt', 'texture_alpha'),
('param_reflect_XXX_spec_hspec', 'texture_alpha'),
('param_occlusion', 'texture')
],
'snd_Map_Build_Basic_Parallax_NC': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('dirt_adjust', 'float', 0.8),
('parallax_amount', 'float', 0.02),
('parallax_dent', 'float', 1.0),
('albedo', 'texture'),
('normal', 'normal'),
('dirt', 'texture_alpha'),
('param_reflect_XXX_height_spec', 'texture_alpha'),
('param_occlusion', 'texture')
],
'snd_Map_Build_DirtScroll': [
('dirt_scale', 'float', 1.0),
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('change_color', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('dirt_adjust', 'float', 0.8),
('albedo', 'texture'),
('normal', 'normal'),
('dirt', 'texture_alpha'),
('param_reflect_cm0_spec_hspec', 'texture_alpha'),
('param_occlusion', 'texture')
],
'snd_Map_Build_DirtScroll_NC': [
('dirt_scale', 'float', 1.0),
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('dirt_adjust', 'float', 0.8),
('albedo', 'texture'),
('normal', 'normal'),
('dirt', 'texture_alpha'),
('param_reflect_XXX_spec_hspec', 'texture_alpha'),
('param_occlusion', 'texture')
],
'snd_Map_Build_DirtScroll_Parallax_NC': [
('dirt_scale', 'float', 1.0),
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('dirt_adjust', 'float', 0.8),
('parallax_amount', 'float', 0.02),
('parallax_dent', 'float', 1.0),
('albedo', 'texture'),
('normal', 'normal'),
('dirt', 'texture_alpha'),
('param_reflect_XXX_height_spec', 'texture_alpha'),
('param_occlusion', 'texture')
],
'snd_Map_Build_Light_NC': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('light_color', 'float3', (4.0, 0.5, 0.5)),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('dirt_adjust', 'float', 0.8),
('albedo', 'texture'),
('normal', 'normal'),
('dirt', 'texture_alpha'),
('param_reflect_light_spec_hspec', 'texture_alpha'),
('param_occlusion', 'texture')
],
'snd_Map_Build_NoOcc': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('dirt_adjust', 'float', 0.8),
('albedo', 'texture'),
('normal', 'normal'),
('dirt', 'texture_alpha'),
('param_reflect_XXX_spec_hspec', 'texture_alpha')
],
'snd_Map_Build_Simple': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_XXX_spec_hspec', 'texture_alpha')
],
'snd_Map_Build_Simple_Alpha': [
('diffuse', 'float4', (1.0, 1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('translucent_fall_off_amount', 'float', 1.0),
('translucent_fall_off_scale', 'float', 1.0),
('translucent_fall_off_offset', 'float', 1.0),
('albedo', 'texture_alpha'),
('normal', 'normal'),
('param_reflect_XXX_spec_hspec', 'texture_alpha'),
('param_occlusion', 'texture')
],
'snd_Map_Build_Simple_Clip': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('alpha_clip', 'float', 0.0),
('albedo', 'texture_alpha'),
('normal', 'normal'),
('param_reflect_XXX_spec_hspec', 'texture_alpha'),
('param_occlusion', 'texture')
],
'snd_Map_Build_Window': [
('window_normal_uv_scale', 'float2', (1.0, 1.0)),
('interior_wrap_count', 'int', 5.605193857299268e-45),
('interior_random_seed', 'float', 0.0),
('normal_amount', 'float2', (1.0, 1.0)),
('window_normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('window_frame_texture', 'texture_alpha'),
('interior_texture', 'texture'),
('normal', 'normal'),
('window_normal', 'normal'),
('param_reflect_XXX_spec_hspec', 'texture_alpha')
],
'snd_Map_Cave_NoOcc': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('min_depth', 'float', 0.0),
('max_depth', 'float', 50.0),
('diffuse_depth_color', 'float3', (1.0, 0.0, 0.0)),
('specular_depth_color', 'float3', (0.5, 0.5, 2.0)),
('specular_depth_effect', 'float', 10.0),
('env_depth_effect', 'float', 10.0),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('dirt_adjust', 'float', 0.8),
('albedo', 'texture'),
('normal', 'normal'),
('dirt', 'texture_alpha'),
('param_reflect_XXX_spec_hspec', 'texture_alpha')
],
'snd_Map_Field_Basic': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('dirt_adjust', 'float', 0.8),
('albedo', 'texture'),
('normal', 'normal'),
('dirt', 'texture_alpha'),
('param_XXX_XXX_spec_hspec', 'texture_alpha')
],
'snd_Map_Field_Parallax': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('dirt_adjust', 'float', 0.8),
('parallax_amount', 'float', 0.02),
('parallax_dent', 'float', 0.5),
('albedo', 'texture'),
('normal', 'normal'),
('dirt', 'texture_alpha'),
('param_XXX_height_spec_hspec', 'texture_alpha')
],
'snd_Map_LOD': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('albedo', 'texture'),
('param_reflect_XXX_spec_hspec', 'texture_alpha')
],
'snd_Map_LOD_CC': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('change_color', 'float3', (1.0, 1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('albedo', 'texture'),
('param_reflect_cm0_spec_hspec', 'texture_alpha')
],
'snd_Map_LOD_CC_NoEnv': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('change_color', 'float3', (1.0, 1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('albedo', 'texture'),
('param_XXX_cm0_spec_hspec', 'texture_alpha')
],
'snd_Map_LOD_NoEnv': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('albedo', 'texture'),
('param_XXX_XXX_spec_XXX', 'texture')
],
'snd_Map_Object': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('change_color', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_cm0_spec_hspec', 'texture_alpha'),
('param_occlusion', 'texture')
],
'snd_Map_Object_Glass': [
('diffuse', 'float4', (1.0, 1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('translucent_fall_off_amount', 'float', 1.0),
('translucent_fall_off_scale', 'float', 1.0),
('translucent_fall_off_offset', 'float', 1.0),
('albedo', 'texture_alpha'),
('normal', 'normal'),
('param_reflect_XXX_spec_hspec', 'texture_alpha')
],
'snd_Map_Object_NoAO': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('change_color', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_cm0_spec_hspec', 'texture_alpha')
],
'snd_Map_Object_NoAO_Clip': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('change_color', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('alpha_clip', 'float', 0.0),
('albedo', 'texture_alpha'),
('normal', 'normal'),
('param_reflect_cm0_spec_hspec', 'texture_alpha')
],
'snd_Map_Object_NoAO_Dirt': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('change_color', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('dirt_adjust', 'float', 0.8),
('albedo', 'texture'),
('normal', 'normal'),
('dirt', 'texture_alpha'),
('param_reflect_cm0_spec_hspec', 'texture_alpha')
],
'snd_Map_Object_NoAO_Light': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('light_color', 'float3', (4.0, 0.5, 0.5)),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_lightmask_hlightmask', 'texture_alpha'),
('param_occlusion', 'texture')
],
'snd_Map_Object_NoCC': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_XXX_spec_hspec', 'texture_alpha'),
('param_occlusion', 'texture')
],
'snd_Map_Object_NoCCAO': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_XXX_spec_hspec', 'texture_alpha')
],
'snd_Map_Simple_Clip': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('alpha_clip', 'float', 0.0),
('albedo', 'texture_alpha')
],
'snd_Map_Tree': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_XXX_spec_hspec', 'texture_alpha')
],
'snd_Map_water_transparent': [
('normal1_scroll_speed', 'float2', (0.08, -0.016)),
('normal1_uv_scale', 'float', 0.1),
('normal2_scroll_speed', 'float2', (0.006, 0.016)),
('normal2_uv_scale', 'float', 1.0),
('normal3_scroll_speed', 'float2', (0.004, 0.008)),
('normal3_uv_scale', 'float', 4.0),
('water_color', 'float4', (0.376, 0.384, 0.937, 1.0)),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('specular_pow', 'float', 100.0),
('environment_reflection', 'float', 0.45),
('normal1_amount', 'float', 1.0),
('parallax1_amount', 'float', 1.0),
('parallax1_offset', 'float', 0.5),
('normal2_amount', 'float', 0.2),
('parallax2_amount', 'float', 0.2),
('parallax2_offset', 'float', 0.5),
('normal3_amount', 'float', 0.5),
('parallax3_amount', 'float', 0.1),
('parallax3_offset', 'float', 0.5),
('bubble_height', 'float', 0.5),
('bubble_amount', 'float', 5.0),
('buble_direction_adjust', 'float', 0.8),
('bubble_uv_scale', 'float', 10.0),
('bubble_diffuse', 'float3', (0.376, 0.384, 0.937)),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('normal_map1', 'normal'),
('normal_map2', 'normal'),
('normal_map3', 'normal'),
('parallax_map1', 'texture'),
('parallax_map2', 'texture'),
('parallax_map3', 'texture'),
('bubble_albedo', 'texture')
],
'snd_Mech': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_XXX_hspec', 'texture_alpha'),
('param_occ_XXX_XXX_XXX', 'texture')
],
'snd_Mech_Catapillar': [
('scroll_texture', 'float2', (0.0, 0.0)),
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('alpha_clip', 'float', 0.0),
('albedo', 'texture_alpha'),
('normal', 'normal'),
('param_reflect_spec_XXX_XXX', 'texture'),
('param_occlusion', 'texture')
],
'snd_Mech_Light': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('light_color', 'float3', (4.0, 0.5, 0.5)),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_lightmask_hlightmask', 'texture_alpha'),
('param_occlusion', 'texture')
],
'snd_Mech_Light_damage': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('light_color', 'float3', (4.0, 0.5, 0.5)),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('damage_uv_mul', 'float2', (10.0, 10.0)),
('damage_mask_uv_mul', 'float2', (10.0, 10.0)),
('damage_normal_amount', 'float', 1.0),
('damage_specular_pow', 'float', 100.0),
('damage_specular_color', 'float3', (1.0, 1.0, 1.0)),
('damage_edge_color', 'float3', (1.0, 1.0, 1.0)),
('damage_max_color', 'float3', (0.2, 0.1, 0.1)),
('damage_reflection', 'float', 0.0),
('damage_metallic', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_lightmask_hlightmask', 'texture_alpha'),
('param_occlusion', 'texture'),
('damage_dist', 'texture'),
('damage_diffuse', 'texture'),
('damage_normal', 'normal')
],
'snd_Mech_damage': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('damage_uv_mul', 'float2', (10.0, 10.0)),
('damage_mask_uv_mul', 'float2', (10.0, 10.0)),
('damage_normal_amount', 'float', 1.0),
('damage_specular_pow', 'float', 100.0),
('damage_specular_color', 'float3', (1.0, 1.0, 1.0)),
('damage_edge_color', 'float3', (1.0, 1.0, 1.0)),
('damage_max_color', 'float3', (0.2, 0.1, 0.1)),
('damage_reflection', 'float', 0.0),
('damage_metallic', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_XXX_hspec', 'texture_alpha'),
('param_occ_XXX_XXX_XXX', 'texture'),
('damage_dist', 'texture'),
('damage_diffuse', 'texture'),
('damage_normal', 'normal')
],
'snd_ShieldBearer_BeamShield': [
('scroll_tex', 'float2', (0.0, 0.0)),
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('light_fall_off_amount', 'float', 1.0),
('light_fall_off_scale', 'float', 1.0),
('light_fall_off_offset', 'float', 0.0),
('alpha', 'float', 1.0),
('edge_color', 'float3', (40.0, 20.0, 20.0)),
('edge_distance', 'float', 2.0),
('edge_fade_distance', 'float', 5.0),
('albedo', 'texture_alpha'),
('normal', 'normal'),
('param_spec_reflect_XXX_XXX', 'texture')
],
'snd_SoftMech': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_XXX_hspec', 'texture_alpha'),
('param_occ_XXX_XXX_XXX', 'texture')
],
'snd_UFO_LightScroll': [
('scroll_light0', 'float2', (0.0, 0.0)),
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('light0_color', 'float3', (4.0, 0.5, 0.5)),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_light0mask_hlight0mask', 'texture_alpha'),
('light0_scroll', 'texture')
],
'snd_UFO_LightScroll2_alpha': [
('scroll_light0', 'float2', (0.0, 0.0)),
('scroll_light1', 'float2', (0.0, 0.0)),
('diffuse', 'float4', (1.0, 1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('light0_color', 'float3', (4.0, 0.5, 0.5)),
('light1_color', 'float3', (0.5, 0.5, 2.0)),
('translucent_fall_off_amount', 'float', 1.0),
('translucent_fall_off_scale', 'float', 1.0),
('translucent_fall_off_offset', 'float', 1.0),
('albedo', 'texture_alpha'),
('normal', 'normal'),
('param_reflect_spec_light0mask_hlight0mask', 'texture_alpha'),
('light0_scroll', 'texture'),
('light1_scroll', 'texture')
],
'snd_UFO_LightScroll2_alpha_damage': [
('scroll_light0', 'float2', (0.0, 0.0)),
('scroll_light1', 'float2', (0.0, 0.0)),
('diffuse', 'float4', (1.0, 1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('light0_color', 'float3', (4.0, 0.5, 0.5)),
('light1_color', 'float3', (0.5, 0.5, 2.0)),
('translucent_fall_off_amount', 'float', 1.0),
('translucent_fall_off_scale', 'float', 1.0),
('translucent_fall_off_offset', 'float', 1.0),
('damage_uv_mul', 'float2', (10.0, 10.0)),
('damage_mask_uv_mul', 'float2', (10.0, 10.0)),
('damage_normal_amount', 'float', 1.0),
('damage_specular_pow', 'float', 100.0),
('damage_specular_color', 'float3', (1.0, 1.0, 1.0)),
('damage_reflection', 'float', 0.0),
('damage_metallic', 'float', 0.0),
('albedo', 'texture_alpha'),
('normal', 'normal'),
('param_reflect_spec_light0mask_hlight0mask', 'texture_alpha'),
('light0_scroll', 'texture'),
('light1_scroll', 'texture'),
('damage_dist', 'texture'),
('damage_diffuse', 'texture_alpha'),
('damage_normal', 'normal')
],
'snd_UFO_LightScroll_damage': [
('scroll_light0', 'float2', (0.0, 0.0)),
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('light0_color', 'float3', (4.0, 0.5, 0.5)),
('damage_uv_mul', 'float2', (10.0, 10.0)),
('damage_mask_uv_mul', 'float2', (10.0, 10.0)),
('damage_normal_amount', 'float', 1.0),
('damage_specular_pow', 'float', 100.0),
('damage_specular_color', 'float3', (1.0, 1.0, 1.0)),
('damage_edge_color', 'float3', (1.0, 1.0, 1.0)),
('damage_max_color', 'float3', (0.2, 0.1, 0.1)),
('damage_reflection', 'float', 0.0),
('damage_metallic', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_light0mask_hlight0mask', 'texture_alpha'),
('light0_scroll', 'texture'),
('damage_dist', 'texture'),
('damage_diffuse', 'texture'),
('damage_normal', 'normal')
],
'snd_UI_Clipping_UVAnim': [
('uv_scale_center0', 'float2', (0.0, 0.0)),
('uv_scale0', 'float2', (1.0, 1.0)),
('uv_scroll0', 'float2', (0.0, 0.0)),
('uv_scale_center1', 'float2', (0.0, 0.0)),
('uv_scale1', 'float2', (1.0, 1.0)),
('uv_scroll1', 'float2', (0.0, 0.0)),
('color0', 'float4', (1.0, 1.0, 1.0, 1.0)),
('prog_control_color', 'float4', (1.0, 1.0, 1.0, 1.0)),
('albedo0', 'texture_alpha'),
('albedo1', 'texture_alpha')
],
'snd_UI_GaugeBar': [
('color', 'float4', (1.0, 1.0, 1.0, 1.0)),
('prog_control_color', 'float4', (1.0, 1.0, 1.0, 1.0)),
('threshold', 'float', 1.0),
('albedo', 'texture_alpha'),
('bar_mask', 'texture')
],
'snd_UI_HSVGradiant': [
('color', 'float4', (1.0, 1.0, 1.0, 1.0)),
('prog_control_color_1', 'float4', (1.0, 1.0, 1.0, 1.0)),
('prog_control_color_2', 'float4', (1.0, 1.0, 1.0, 1.0)),
('albedo', 'texture_alpha')
],
'snd_UI_HSVHue': [
('color', 'float4', (1.0, 1.0, 1.0, 1.0)),
('prog_control_color', 'float4', (1.0, 1.0, 1.0, 1.0)),
('albedo', 'texture_alpha')
],
'snd_UI_Simple': [
('color', 'float4', (1.0, 1.0, 1.0, 1.0)),
('prog_control_color', 'float4', (1.0, 1.0, 1.0, 1.0)),
('albedo', 'texture_alpha')
],
'snd_UI_Simple_UVAnim': [
('color', 'float4', (1.0, 1.0, 1.0, 1.0)),
('prog_control_color', 'float4', (1.0, 1.0, 1.0, 1.0)),
('uv_scale_center', 'float2', (0.0, 0.0)),
('uv_scale', 'float2', (1.0, 1.0)),
('uv_scroll', 'float2', (0.0, 0.0)),
('albedo', 'texture_alpha')
],
'snd_UI_Solid': [
('base_color', 'float4', (0.5, 0.5, 0.5, 1.0)),
('mul_color', 'float4', (1.0, 1.0, 1.0, 1.0))
],
'snd_e505_Flare': [
('color0', 'float4', (1.0, 1.0, 1.0, 1.0)),
('color1', 'float4', (1.0, 1.0, 1.0, 1.0)),
('uv_scroll0', 'float2', (0.0, 0.0)),
('uv_scroll1', 'float2', (0.0, 0.0)),
('albedo0', 'texture_alpha'),
('mask0', 'texture'),
('albedo1', 'texture_alpha'),
('mask1', 'texture')
],
'snd_e511_Unit_Surface': [
('diffuse', 'float3', (1.0, 1.0, 1.0)),
('normal_amount', 'float2', (1.0, 1.0)),
('specular_pow', 'float', 100.0),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('light_smooth', 'float', 0.0),
('metallic', 'float', 0.0),
('roughness', 'float', 0.0),
('fall_off_amount', 'float', 1.0),
('fall_off_scale', 'float', 1.0),
('fall_off_offset', 'float', 0.0),
('damage_uv_mul', 'float2', (1.0, 1.0)),
('damage_mask_uv_mul', 'float2', (1.0, 1.0)),
('damage_normal_amount', 'float', 1.0),
('damage_specular_pow', 'float', 100.0),
('damage_specular_color', 'float3', (1.0, 1.0, 1.0)),
('damage_edge_color', 'float3', (1.0, 1.0, 1.0)),
('damage_max_color', 'float3', (0.2, 0.1, 0.1)),
('damage_reflection', 'float', 0.0),
('damage_metallic', 'float', 0.0),
('albedo', 'texture'),
('normal', 'normal'),
('param_reflect_spec_occ', 'texture'),
('damage_diffuse', 'texture'),
('damage_normal', 'normal'),
('damage_dist', 'texture')
],
'test_damage_map': [
('color', 'float3', (1.0, 1.0, 1.0)),
('specular_color', 'float3', (1.0, 1.0, 1.0)),
('specular_pow', 'float', 100.0),
('smooth', 'float', 0.0),
('damage_normal_amount', 'float', 1.0),
('damage_pallax_amount', 'float', 0.05),
('damage_amount', 'float', 1.0),
('damage_dist', 'texture'),
('damage_diffuse', 'texture'),
('damage_normal', 'normal')
]
}
